### PR TITLE
Implemented Selection Sort using Java

### PR DESCRIPTION
**Pull request by srushtips**
Added the code and output image in the selection sort folder.

### CODE REVIEW

**Review by sparsh-99 — CHANGES_REQUESTED** [review]
@srushtips, No need to conflict the files already in that folder made by me. Just put the code in **General folder only**.

**Comment by srushtips** [comment]
Hi, I have made the requested changes!

**Comment by sparsh-99** [comment]
> Hi, I have made the requested changes!

Also, rename the file in the format given in issue #12. Please read the guidelines carefully before making PR

**Review by sparsh-99 — APPROVED** [review]
Now, they are good to go :)

**Comment by srushtips** [comment]
Great! Sorry about that!

**Comment by sparsh-99** [comment]
> Great! Sorry about that!

No issue 👍

**Pull request merged**
