### PR TITLE
Moved the Array Reverse in Group Algo to General folder

### PR DESCRIPTION
**Pull request by xyther14**
Hope this is in line with the guidelines and will be merged.

### CODE REVIEW

**Review by sparsh-99 — CHANGES_REQUESTED** [review]
No coding in C @xyther14 is accepted here.... Only C++ and java. So, plz delete the c file.

**Comment by xyther14** [comment]
> No coding in C @xyther14 is accepted here.... Only C++ and java. So, plz delete the c file.

It is a Java file.

**Comment by sparsh-99** [comment]
> > No coding in C @xyther14 is accepted here.... Only C++ and java. So, plz delete the c file.
> 
> It is a Java file.

Please check the commit named "Added the algo to General folder".

**Comment by sparsh-99** [comment]
> > > No coding in C @xyther14 is accepted here.... Only C++ and java. So, plz delete the c file.
> > 
> > 
> > It is a Java file.
> 
> Please check the commit named "Added the algo to General folder".

But leave it, I will accept it... Good work @xyther14

**Review by sparsh-99 — APPROVED** [review]

**Pull request merged**
