### PR TITLE
Adding Array Reverse in group algorithm

### PR DESCRIPTION
**Pull request by xyther14**
Adding the algorithm for Reversing array in groups.

### CODE REVIEW

**Review by sparsh-99 — COMMENTED** [review]
I can see lots of files in this commit. Remove them from this PR and do request only with your code file.

**Review by sparsh-99 — COMMENTED** [review]
No need of .idea/.gitignore or .idea/ds-algo.iml type files. be specific

**Comment by xyther14** [comment]
Sorry for the trouble, this was my first PR so I was not sure. Should I just push my directory?

**Comment by sparsh-99** [comment]
> Sorry for the trouble, this was my first PR so I was not sure. Should I just push my directory?

Just push your main java file, not full directory.

**Comment by xyther14** [comment]
> > Sorry for the trouble, this was my first PR so I was not sure. Should I just push my directory?
> 
> Just push your main java file, not full directory.

Should I close this PR and request a new one?

**Comment by sparsh-99** [comment]
> > > Sorry for the trouble, this was my first PR so I was not sure. Should I just push my directory?
> > 
> > 
> > Just push your main java file, not full directory.
> 
> Should I close this PR and request a new one?

If you would like to, u can go on

**Pull request closed without merging**
